### ISSUE TITLE
RQ5: How do plans generated with BELLTREE compare with other planners?

### ISSUE THREAD

**Issue by rahlk** [ai-se/xtree-plan#54]
# ANT 
![image](https://user-images.githubusercontent.com/1433964/40262494-cd8f9bb0-5ad5-11e8-95d9-09428ed392a2.png)
# CAMEL
![image](https://user-images.githubusercontent.com/1433964/40262510-e47aec1c-5ad5-11e8-89d8-759c900494e0.png)
# IVY
![image](https://user-images.githubusercontent.com/1433964/40262526-fecaaa8a-5ad5-11e8-85fa-9ea05869a024.png)
# JEDIT
![image](https://user-images.githubusercontent.com/1433964/40262550-3159c026-5ad6-11e8-872a-a7b4b8d79582.png)
# LOG4J
![image](https://user-images.githubusercontent.com/1433964/40262535-127cecaa-5ad6-11e8-9fb6-06ad275e7eaa.png)
# POI
![image](https://user-images.githubusercontent.com/1433964/40262662-194793ea-5ad7-11e8-9d75-ff2325dd404e.png)
# VELOCITY
![image](https://user-images.githubusercontent.com/1433964/40262666-271a9ee0-5ad7-11e8-87bb-aa73b5b8261e.png)
# XALAN
![image](https://user-images.githubusercontent.com/1433964/40262676-41f44e46-5ad7-11e8-835a-691bb84577f4.png)
# XERCES
![image](https://user-images.githubusercontent.com/1433964/40262684-529a9d68-5ad7-11e8-8751-48786040968a.png)

**Comment by timm** [comment]
i thought we  were only as good as oliveria?

**Comment by rahlk** [comment]
Still true (xalan, velocity, poi, and log4j) , but not in all subsets, and not when we plot out the thresholds explicitly.

**Comment by rahlk** [comment]
By the way this is plan on Bellwether test on datasets

**Comment by timm** [comment]
do these graphs need a "none" line? thre's too much here to show. just show the last one in each series?

**Comment by timm** [comment]
did u ever do that graninger test?

what is the status of the tse article?

**Comment by rahlk** [comment]
> do these graphs need a "none" line? there's too much here to show. just show the last one in each series?

Not sure of the none line. I do agree that there is too much to show, but there is more. I'm using a "bar chart" to include everything.

I still think there is too much, but I think we can remove all the comparisons and have only XTREE.  

![rq5](https://user-images.githubusercontent.com/1433964/40326940-0f45f15e-5d0f-11e8-8ce3-6eba48c1b013.png)
